#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - bootstrap must be able to install its own deps
    yaml = None  # type: ignore


WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
SITE_CONFIG_PATH = WORKSPACE_ROOT / "control" / "site.yaml"
BOOTSTRAP_STATUS_PATH = WORKSPACE_ROOT / "runtime" / "bootstrap-status.json"
CODEX_CONFIG_PATH = WORKSPACE_ROOT / ".codex" / "config.toml"
REQUIREMENTS_PATH = WORKSPACE_ROOT / "requirements.txt"
PYTHON_DEPENDENCIES = (
    ("yaml", "PyYAML"),
    ("docx", "python-docx"),
    ("openpyxl", "openpyxl"),
    ("pypdf", "pypdf"),
    ("qrcode", "qrcode[pil]"),
    ("certifi", "certifi"),
)


@dataclass
class SiteConfig:
    product_name: str
    workspace_root: Path
    memory_root: Path
    operator_name: str
    timezone: str
    launchagent_prefix: str
    feishu_enabled: bool
    electron_enabled: bool


def app_candidates(name: str) -> list[Path]:
    return [
        Path("/Applications") / f"{name}.app",
        Path.home() / "Applications" / f"{name}.app",
    ]


def app_installed(name: str) -> bool:
    return any(candidate.exists() for candidate in app_candidates(name))


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def resolve_root(raw: object, default: Path) -> Path:
    if raw in (None, "", "auto"):
        return default.resolve()
    path = Path(str(raw)).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (WORKSPACE_ROOT / path).resolve()


def ensure_yaml_available() -> None:
    if yaml is not None:
        return
    raise SystemExit(
        "PyYAML is required to read control/site.yaml. "
        "Run `python3 ops/bootstrap_workspace_hub.py install-python-deps` "
        "or `python3 ops/bootstrap_workspace_hub.py setup` first."
    )


def default_site_config() -> SiteConfig:
    return SiteConfig(
        product_name="Codex Hub",
        workspace_root=WORKSPACE_ROOT.resolve(),
        memory_root=(WORKSPACE_ROOT.parent / "memory").resolve(),
        operator_name="",
        timezone="Asia/Shanghai",
        launchagent_prefix="com.codexhub",
        feishu_enabled=False,
        electron_enabled=True,
    )


def load_site_config() -> SiteConfig:
    if yaml is None:
        return default_site_config()
    if not SITE_CONFIG_PATH.exists():
        return default_site_config()
    raw = yaml.safe_load(SITE_CONFIG_PATH.read_text(encoding="utf-8")) or {}
    site = raw.get("site") or {}
    return SiteConfig(
        product_name=str(site.get("product_name") or default_site_config().product_name),
        workspace_root=resolve_root(site.get("workspace_root"), default_site_config().workspace_root),
        memory_root=resolve_root(site.get("memory_root"), default_site_config().memory_root),
        operator_name=str(site.get("operator_name") or ""),
        timezone=str(site.get("timezone") or default_site_config().timezone),
        launchagent_prefix=str(site.get("launchagent_prefix") or default_site_config().launchagent_prefix),
        feishu_enabled=bool(site.get("feishu_enabled", default_site_config().feishu_enabled)),
        electron_enabled=bool(site.get("electron_enabled", default_site_config().electron_enabled)),
    )


def required_workspace_dirs(workspace_root: Path) -> list[Path]:
    return [
        workspace_root / "runtime",
        workspace_root / "logs",
        workspace_root / "reports" / "system",
        workspace_root / "reports" / "ops",
        workspace_root / "projects",
    ]


def required_memory_dirs(memory_root: Path) -> list[Path]:
    return [
        memory_root / "01_working",
        memory_root / "02_episodic" / "daily",
        memory_root / "03_semantic" / "projects",
        memory_root / "03_semantic" / "systems",
        memory_root / "07_dashboards",
        memory_root / "07_dashboards" / "materials",
    ]


def ensure_dirs(paths: list[Path]) -> None:
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)


def write_codex_config(site: SiteConfig) -> None:
    writable_roots = [
        site.workspace_root,
        site.memory_root,
        site.workspace_root / "projects",
    ]
    rendered = "\n".join(
        [
            "#:schema https://developers.openai.com/codex/config-schema.json",
            "# This file is generated by `python3 ops/bootstrap_workspace_hub.py init`.",
            "",
            'approval_policy = "on-request"',
            'sandbox_mode = "workspace-write"',
            'web_search = "cached"',
            "allow_login_shell = true",
            'personality = "pragmatic"',
            "",
            "[sandbox_workspace_write]",
            "network_access = true",
            "writable_roots = [",
            *[f'  "{path}",' for path in writable_roots],
            "]",
            "exclude_tmpdir_env_var = false",
            "exclude_slash_tmp = false",
            "",
            "[features]",
            "shell_snapshot = true",
            "sqlite = true",
            "unified_exec = true",
            "",
        ]
    )
    CODEX_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CODEX_CONFIG_PATH.write_text(rendered, encoding="utf-8")


def command_available(name: str) -> bool:
    return shutil.which(name) is not None


def python_module_status() -> dict[str, bool]:
    return {module: importlib.util.find_spec(module) is not None for module, _ in PYTHON_DEPENDENCIES}


def missing_python_packages() -> list[str]:
    status = python_module_status()
    return [package for module, package in PYTHON_DEPENDENCIES if not status.get(module, False)]


def run_command(cmd: list[str], cwd: Path) -> dict[str, object]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd),
        text=True,
        capture_output=True,
        check=False,
    )
    return {
        "command": cmd,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def bootstrap_status_payload(site: SiteConfig) -> dict[str, object]:
    return {
        "generated_at": utc_now(),
        "product_name": site.product_name,
        "workspace_root": str(site.workspace_root),
        "memory_root": str(site.memory_root),
        "operator_name": site.operator_name,
        "timezone": site.timezone,
        "launchagent_prefix": site.launchagent_prefix,
        "feishu_enabled": site.feishu_enabled,
        "electron_enabled": site.electron_enabled,
        "commands": {
            "python3": command_available("python3"),
            "node": command_available("node"),
            "npm": command_available("npm"),
            "codex": command_available("codex"),
        },
        "python_modules": python_module_status(),
        "apps": {
            "obsidian": app_installed("Obsidian"),
            "codex_desktop": app_installed("Codex"),
        },
        "files": {
            "site_config": SITE_CONFIG_PATH.exists(),
            "codex_config": CODEX_CONFIG_PATH.exists(),
            "feishu_resources": (site.workspace_root / "control" / "feishu_resources.yaml").exists(),
            "feishu_bridge_env_example": (site.workspace_root / "ops" / "feishu_bridge.env.example").exists(),
        },
        "manual_actions": [],
        "sync_results": {},
        "launchagents": {
            "installed": False,
        },
        "feishu_bridge": {
            "installed": False,
        },
    }


def build_manual_actions(site: SiteConfig, payload: dict[str, object]) -> list[str]:
    actions: list[str] = []
    commands = payload.get("commands", {})
    module_status = payload.get("python_modules", {})
    apps = payload.get("apps", {})
    missing_packages = [package for module, package in PYTHON_DEPENDENCIES if not module_status.get(module, False)]
    if missing_packages:
        actions.append(
            "Install Python dependencies with `python3 ops/bootstrap_workspace_hub.py install-python-deps`."
        )
    if not commands.get("codex"):
        actions.append("Install Codex CLI and complete `codex login`.")
    else:
        actions.append("Run `codex login` once if this machine has not authenticated yet.")
    if not apps.get("codex_desktop"):
        actions.append("Optional but recommended: install the Codex desktop app for direct-open workspace sessions.")
    if not apps.get("obsidian"):
        actions.append("Optional but strongly recommended: install Obsidian for full Vault browsing and `obsidian://` deep-link support.")
    if site.feishu_enabled:
        actions.extend(
            [
                "Fill `control/feishu_resources.yaml` with your app, calendar, table, and alias defaults.",
                "Copy `ops/feishu_bridge.env.example` to `ops/feishu_bridge.env.local` and fill your Feishu app settings.",
                "Complete one Feishu OAuth login with `python3 ops/feishu_agent.py auth login`.",
                "Ensure your CoCo Feishu app scopes are approved and published.",
                "Optionally install the Feishu bridge launch agent with `python3 ops/bootstrap_workspace_hub.py init --install-feishu-bridge`.",
            ]
        )
    else:
        actions.append("Enable Feishu later by setting `site.feishu_enabled: true` after local bootstrap succeeds.")
    return actions


def maybe_sync(site: SiteConfig, skip_sync: bool) -> dict[str, object]:
    if skip_sync:
        return {"skipped": True}
    commands = {
        "refresh_index": ["python3", "ops/codex_memory.py", "refresh-index"],
        "rebuild_dashboards": ["python3", "ops/codex_dashboard_sync.py", "rebuild-all"],
        "verify_consistency": ["python3", "ops/codex_dashboard_sync.py", "verify-consistency"],
    }
    return {name: run_command(cmd, site.workspace_root) for name, cmd in commands.items()}


def install_python_dependencies(*, force: bool = False) -> dict[str, object]:
    missing = missing_python_packages()
    if not missing and not force:
        return {
            "installed": False,
            "skipped": True,
            "missing_packages": [],
            "requirements_path": str(REQUIREMENTS_PATH),
        }
    if REQUIREMENTS_PATH.exists():
        command = [sys.executable, "-m", "pip", "install", "-r", str(REQUIREMENTS_PATH)]
    else:
        command = [sys.executable, "-m", "pip", "install", *missing]
    result = run_command(command, WORKSPACE_ROOT)
    result["installed"] = result.get("returncode") == 0
    result["missing_packages"] = missing
    result["requirements_path"] = str(REQUIREMENTS_PATH)
    result["python_modules_after"] = python_module_status()
    return result


def maybe_install_launchagents(site: SiteConfig, install: bool) -> dict[str, object]:
    if not install:
        return {"installed": False, "skipped": True}
    results = {
        "watcher": run_command(
            ["python3", "ops/codex_session_watcher.py", "install-launchagent", "--poll-interval", "300"],
            site.workspace_root,
        ),
        "dashboard_sync": run_command(
            ["python3", "ops/codex_dashboard_sync.py", "install-launchagent", "--interval", "900"],
            site.workspace_root,
        ),
        "health_check": run_command(
            ["python3", "ops/workspace_hub_health_check.py", "install-launchagent", "--interval", "14400"],
            site.workspace_root,
        ),
        "feishu_projection": run_command(
            ["python3", "ops/feishu_projection.py", "install-launchagent", "--interval", "900"],
            site.workspace_root,
        ),
    }
    return {"installed": True, "results": results}


def maybe_install_feishu_bridge(site: SiteConfig, install: bool) -> dict[str, object]:
    if not install:
        return {"installed": False, "skipped": True}
    if not site.feishu_enabled:
        return {"installed": False, "skipped": True, "reason": "feishu_disabled"}
    console_root = site.workspace_root / "apps" / "electron-console"
    package_json = console_root / "package.json"
    if not package_json.exists():
        return {"installed": False, "skipped": True, "reason": "electron_console_missing"}
    install_result = run_command(["npm", "install"], console_root)
    bridge_result = run_command(["node", "coco-bridge-service.js", "install-launchagent"], console_root)
    return {
        "installed": install_result.get("returncode") == 0 and bridge_result.get("returncode") == 0,
        "results": {
            "npm_install": install_result,
            "bridge_install": bridge_result,
        },
    }


def perform_init(site: SiteConfig, args: argparse.Namespace) -> dict[str, object]:
    ensure_dirs(required_workspace_dirs(site.workspace_root))
    ensure_dirs(required_memory_dirs(site.memory_root))
    write_codex_config(site)

    payload = bootstrap_status_payload(site)
    payload["sync_results"] = maybe_sync(site, skip_sync=args.skip_sync)
    payload["launchagents"] = maybe_install_launchagents(site, install=args.install_launchagents)
    payload["feishu_bridge"] = maybe_install_feishu_bridge(site, install=args.install_feishu_bridge)
    payload["manual_actions"] = build_manual_actions(site, payload)

    BOOTSTRAP_STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    BOOTSTRAP_STATUS_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return payload


def cmd_init(args: argparse.Namespace) -> int:
    site = load_site_config()
    payload = perform_init(site, args)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def cmd_install_python_deps(args: argparse.Namespace) -> int:
    payload = install_python_dependencies(force=args.force)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload.get("installed", True) else 0


def cmd_setup(args: argparse.Namespace) -> int:
    dependency_result = {"installed": False, "skipped": True}
    if not args.skip_python_deps:
        dependency_result = install_python_dependencies(force=args.force_python_deps)
        if dependency_result.get("returncode", 0) != 0:
            print(
                json.dumps(
                    {"ok": False, "stage": "install-python-deps", "python_dependencies": dependency_result},
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return int(dependency_result.get("returncode") or 1)
    site = load_site_config()
    bootstrap_result = perform_init(site, args)
    acceptance_result = {"skipped": True}
    acceptance_rc = 0
    if not args.skip_acceptance:
        acceptance_result = run_command([sys.executable, "ops/accept_product.py", "run"], site.workspace_root)
        acceptance_rc = int(acceptance_result.get("returncode") or 0)
    payload = {
        "ok": acceptance_rc == 0 and dependency_result.get("returncode", 0) == 0,
        "python_dependencies": dependency_result,
        "bootstrap": bootstrap_result,
        "acceptance": acceptance_result,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload["ok"] else 1


def cmd_status(_: argparse.Namespace) -> int:
    site = load_site_config()
    if BOOTSTRAP_STATUS_PATH.exists():
        payload = json.loads(BOOTSTRAP_STATUS_PATH.read_text(encoding="utf-8"))
    else:
        payload = bootstrap_status_payload(site)
        payload["manual_actions"] = build_manual_actions(site, payload)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bootstrap the portable Codex Hub product workspace.")
    sub = parser.add_subparsers(dest="command", required=True)

    install_deps_parser = sub.add_parser(
        "install-python-deps",
        help="Install the Python packages required by bootstrap, acceptance, and bridge helpers.",
    )
    install_deps_parser.add_argument("--force", action="store_true", help="Run pip install even if the modules already exist.")
    install_deps_parser.set_defaults(func=cmd_install_python_deps)

    init_parser = sub.add_parser("init", help="Initialize runtime folders, generated config, and optional launchagents.")
    init_parser.add_argument(
        "--skip-sync",
        action="store_true",
        help="Skip refresh-index / rebuild-all / verify-consistency during bootstrap.",
    )
    init_parser.add_argument(
        "--install-launchagents",
        action="store_true",
        help="Install launchd tasks for watcher, dashboard sync, health check, and Feishu projection.",
    )
    init_parser.add_argument(
        "--install-feishu-bridge",
        action="store_true",
        help="Run npm install for Electron and install the Feishu bridge launch agent.",
    )
    init_parser.set_defaults(func=cmd_init)

    setup_parser = sub.add_parser(
        "setup",
        help="Install Python dependencies, run bootstrap, and then run acceptance in one command.",
    )
    setup_parser.add_argument(
        "--skip-python-deps",
        action="store_true",
        help="Skip the Python dependency installation stage.",
    )
    setup_parser.add_argument(
        "--force-python-deps",
        action="store_true",
        help="Force reinstall Python dependencies before bootstrap.",
    )
    setup_parser.add_argument(
        "--skip-sync",
        action="store_true",
        help="Skip refresh-index / rebuild-all / verify-consistency during bootstrap.",
    )
    setup_parser.add_argument(
        "--install-launchagents",
        action="store_true",
        help="Install launchd tasks for watcher, dashboard sync, health check, and Feishu projection.",
    )
    setup_parser.add_argument(
        "--install-feishu-bridge",
        action="store_true",
        help="Run npm install for Electron and install the Feishu bridge launch agent.",
    )
    setup_parser.add_argument(
        "--skip-acceptance",
        action="store_true",
        help="Skip the final acceptance run after bootstrap.",
    )
    setup_parser.set_defaults(func=cmd_setup)

    status_parser = sub.add_parser("status", help="Show the latest bootstrap status snapshot.")
    status_parser.set_defaults(func=cmd_status)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
