#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

import yaml


WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
SITE_CONFIG_PATH = WORKSPACE_ROOT / "control" / "site.yaml"
BOOTSTRAP_STATUS_PATH = WORKSPACE_ROOT / "runtime" / "bootstrap-status.json"
CODEX_CONFIG_PATH = WORKSPACE_ROOT / ".codex" / "config.toml"


@dataclass
class SiteConfig:
    product_name: str
    workspace_root: Path
    memory_root: Path
    operator_name: str
    timezone: str
    launchagent_prefix: str
    feishu_enabled: bool
    electron_enabled: bool


def app_candidates(name: str) -> list[Path]:
    return [
        Path("/Applications") / f"{name}.app",
        Path.home() / "Applications" / f"{name}.app",
    ]


def app_installed(name: str) -> bool:
    return any(candidate.exists() for candidate in app_candidates(name))


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def resolve_root(raw: object, default: Path) -> Path:
    if raw in (None, "", "auto"):
        return default.resolve()
    path = Path(str(raw)).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (WORKSPACE_ROOT / path).resolve()


def load_site_config() -> SiteConfig:
    raw = yaml.safe_load(SITE_CONFIG_PATH.read_text(encoding="utf-8")) or {}
    site = raw.get("site") or {}
    return SiteConfig(
        product_name=str(site.get("product_name") or "Codex Hub"),
        workspace_root=resolve_root(site.get("workspace_root"), WORKSPACE_ROOT),
        memory_root=resolve_root(site.get("memory_root"), WORKSPACE_ROOT.parent / "memory"),
        operator_name=str(site.get("operator_name") or ""),
        timezone=str(site.get("timezone") or "Asia/Shanghai"),
        launchagent_prefix=str(site.get("launchagent_prefix") or "com.codexhub"),
        feishu_enabled=bool(site.get("feishu_enabled", False)),
        electron_enabled=bool(site.get("electron_enabled", True)),
    )


def required_workspace_dirs(workspace_root: Path) -> list[Path]:
    return [
        workspace_root / "runtime",
        workspace_root / "logs",
        workspace_root / "reports" / "system",
        workspace_root / "reports" / "ops",
        workspace_root / "projects",
    ]


def required_memory_dirs(memory_root: Path) -> list[Path]:
    return [
        memory_root / "01_working",
        memory_root / "02_episodic" / "daily",
        memory_root / "03_semantic" / "projects",
        memory_root / "03_semantic" / "systems",
        memory_root / "07_dashboards",
        memory_root / "07_dashboards" / "materials",
    ]


def ensure_dirs(paths: list[Path]) -> None:
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)


def write_codex_config(site: SiteConfig) -> None:
    writable_roots = [
        site.workspace_root,
        site.memory_root,
        site.workspace_root / "projects",
    ]
    rendered = "\n".join(
        [
            "#:schema https://developers.openai.com/codex/config-schema.json",
            "# This file is generated by `python3 ops/bootstrap_workspace_hub.py init`.",
            "",
            'approval_policy = "on-request"',
            'sandbox_mode = "workspace-write"',
            'web_search = "cached"',
            "allow_login_shell = true",
            'personality = "pragmatic"',
            "",
            "[sandbox_workspace_write]",
            "network_access = true",
            "writable_roots = [",
            *[f'  "{path}",' for path in writable_roots],
            "]",
            "exclude_tmpdir_env_var = false",
            "exclude_slash_tmp = false",
            "",
            "[features]",
            "shell_snapshot = true",
            "sqlite = true",
            "unified_exec = true",
            "",
        ]
    )
    CODEX_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CODEX_CONFIG_PATH.write_text(rendered, encoding="utf-8")


def command_available(name: str) -> bool:
    return shutil.which(name) is not None


def run_command(cmd: list[str], cwd: Path) -> dict[str, object]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd),
        text=True,
        capture_output=True,
        check=False,
    )
    return {
        "command": cmd,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def bootstrap_status_payload(site: SiteConfig) -> dict[str, object]:
    return {
        "generated_at": utc_now(),
        "product_name": site.product_name,
        "workspace_root": str(site.workspace_root),
        "memory_root": str(site.memory_root),
        "operator_name": site.operator_name,
        "timezone": site.timezone,
        "launchagent_prefix": site.launchagent_prefix,
        "feishu_enabled": site.feishu_enabled,
        "electron_enabled": site.electron_enabled,
        "commands": {
            "python3": command_available("python3"),
            "node": command_available("node"),
            "npm": command_available("npm"),
            "codex": command_available("codex"),
        },
        "apps": {
            "obsidian": app_installed("Obsidian"),
            "codex_desktop": app_installed("Codex"),
        },
        "files": {
            "site_config": SITE_CONFIG_PATH.exists(),
            "codex_config": CODEX_CONFIG_PATH.exists(),
            "feishu_resources": (site.workspace_root / "control" / "feishu_resources.yaml").exists(),
            "feishu_bridge_env_example": (site.workspace_root / "ops" / "feishu_bridge.env.example").exists(),
        },
        "manual_actions": [],
        "sync_results": {},
        "launchagents": {
            "installed": False,
        },
        "feishu_bridge": {
            "installed": False,
        },
    }


def build_manual_actions(site: SiteConfig, payload: dict[str, object]) -> list[str]:
    actions: list[str] = []
    commands = payload.get("commands", {})
    apps = payload.get("apps", {})
    if not commands.get("codex"):
        actions.append("Install Codex CLI and complete `codex login`.")
    else:
        actions.append("Run `codex login` once if this machine has not authenticated yet.")
    if not apps.get("codex_desktop"):
        actions.append("Optional but recommended: install the Codex desktop app for direct-open workspace sessions.")
    if not apps.get("obsidian"):
        actions.append("Optional but strongly recommended: install Obsidian for full Vault browsing and `obsidian://` deep-link support.")
    if site.feishu_enabled:
        actions.extend(
            [
                "Fill `control/feishu_resources.yaml` with your app, calendar, table, and alias defaults.",
                "Copy `ops/feishu_bridge.env.example` to `ops/feishu_bridge.env.local` and fill your Feishu app settings.",
                "Complete one Feishu OAuth login with `python3 ops/feishu_agent.py auth login`.",
                "Ensure your CoCo Feishu app scopes are approved and published.",
                "Optionally install the Feishu bridge launch agent with `python3 ops/bootstrap_workspace_hub.py init --install-feishu-bridge`.",
            ]
        )
    else:
        actions.append("Enable Feishu later by setting `site.feishu_enabled: true` after local bootstrap succeeds.")
    return actions


def maybe_sync(site: SiteConfig, skip_sync: bool) -> dict[str, object]:
    if skip_sync:
        return {"skipped": True}
    commands = {
        "refresh_index": ["python3", "ops/codex_memory.py", "refresh-index"],
        "rebuild_dashboards": ["python3", "ops/codex_dashboard_sync.py", "rebuild-all"],
        "verify_consistency": ["python3", "ops/codex_dashboard_sync.py", "verify-consistency"],
    }
    return {name: run_command(cmd, site.workspace_root) for name, cmd in commands.items()}


def maybe_install_launchagents(site: SiteConfig, install: bool) -> dict[str, object]:
    if not install:
        return {"installed": False, "skipped": True}
    results = {
        "watcher": run_command(
            ["python3", "ops/codex_session_watcher.py", "install-launchagent", "--interval", "300"],
            site.workspace_root,
        ),
        "dashboard_sync": run_command(
            ["python3", "ops/codex_dashboard_sync.py", "install-launchagent", "--interval", "900"],
            site.workspace_root,
        ),
        "health_check": run_command(
            ["python3", "ops/workspace_hub_health_check.py", "install-launchagent", "--interval", "14400"],
            site.workspace_root,
        ),
        "feishu_projection": run_command(
            ["python3", "ops/feishu_projection.py", "install-launchagent", "--interval", "900"],
            site.workspace_root,
        ),
    }
    return {"installed": True, "results": results}


def maybe_install_feishu_bridge(site: SiteConfig, install: bool) -> dict[str, object]:
    if not install:
        return {"installed": False, "skipped": True}
    if not site.feishu_enabled:
        return {"installed": False, "skipped": True, "reason": "feishu_disabled"}
    console_root = site.workspace_root / "apps" / "electron-console"
    package_json = console_root / "package.json"
    if not package_json.exists():
        return {"installed": False, "skipped": True, "reason": "electron_console_missing"}
    install_result = run_command(["npm", "install"], console_root)
    bridge_result = run_command(["node", "coco-bridge-service.js", "install-launchagent"], console_root)
    return {
        "installed": install_result.get("returncode") == 0 and bridge_result.get("returncode") == 0,
        "results": {
            "npm_install": install_result,
            "bridge_install": bridge_result,
        },
    }


def cmd_init(args: argparse.Namespace) -> int:
    site = load_site_config()
    ensure_dirs(required_workspace_dirs(site.workspace_root))
    ensure_dirs(required_memory_dirs(site.memory_root))
    write_codex_config(site)

    payload = bootstrap_status_payload(site)
    payload["sync_results"] = maybe_sync(site, skip_sync=args.skip_sync)
    payload["launchagents"] = maybe_install_launchagents(site, install=args.install_launchagents)
    payload["feishu_bridge"] = maybe_install_feishu_bridge(site, install=args.install_feishu_bridge)
    payload["manual_actions"] = build_manual_actions(site, payload)

    BOOTSTRAP_STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    BOOTSTRAP_STATUS_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def cmd_status(_: argparse.Namespace) -> int:
    site = load_site_config()
    if BOOTSTRAP_STATUS_PATH.exists():
        payload = json.loads(BOOTSTRAP_STATUS_PATH.read_text(encoding="utf-8"))
    else:
        payload = bootstrap_status_payload(site)
        payload["manual_actions"] = build_manual_actions(site, payload)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bootstrap the portable Codex Hub product workspace.")
    sub = parser.add_subparsers(dest="command", required=True)

    init_parser = sub.add_parser("init", help="Initialize runtime folders, generated config, and optional launchagents.")
    init_parser.add_argument(
        "--skip-sync",
        action="store_true",
        help="Skip refresh-index / rebuild-all / verify-consistency during bootstrap.",
    )
    init_parser.add_argument(
        "--install-launchagents",
        action="store_true",
        help="Install launchd tasks for watcher, dashboard sync, health check, and Feishu projection.",
    )
    init_parser.add_argument(
        "--install-feishu-bridge",
        action="store_true",
        help="Run npm install for Electron and install the Feishu bridge launch agent.",
    )
    init_parser.set_defaults(func=cmd_init)

    status_parser = sub.add_parser("status", help="Show the latest bootstrap status snapshot.")
    status_parser.set_defaults(func=cmd_status)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
